### ISSUE TITLE
Last post link missing pagination

### ISSUE THREAD

**Issue by Monsieur2M** [phpBBSEO/nodupe#3]
Hello,

Seems to have a bug with last post and unread post rewriting, pagination is missing.
Thanks.

**Comment by dcz** [comment]
Here : https://github.com/phpBBSEO/nodupe/pull/4
Requires latest USU (I just fixed a notice related to fixing this one : https://github.com/phpBBSEO/usu/pull/49)

**Comment by Monsieur2M** [comment]
It seems that viewforum links are OK now, but there's another bug : when you submit a new reply, you are redirected to the first post and not to the reply you've just wrote.

**Comment by dcz** [comment]
it seems to be in USU, let me check.
